version: "3"
services:
  metabase:
    container_name: metabase
    image: metabase/metabase:v0.32.9
    ports:
      - "3000:3000"
    volumes:
      - ./tmp:/tmp
    links:
      - psql
    environment:
      MB_DB_FILE: "/tmp/metabase.db"
  psql:
    image: postgres:11.5
    container_name: postgresql
    ports:
      - 5432:5432
    volumes:
      - ./initdb.d/video_app.sql.gz:/docker-entrypoint-initdb.d/video_app.sql.gz
    environment:
      POSTGRES_DB: video_app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
    
